version: '3.4'

services:
  tnosc.shop.server.bootstrapper:
    image: ${DOCKER_REGISTRY-}tnoscshopserverbootstrapper
    build:
      context: .
      dockerfile: src/Host/Tnosc.Shop.Server.Bootstrapper/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  tnosc.Shop.Client.Host.Web:
    image: ${DOCKER_REGISTRY-}tnoscshophostweb
    build:
      context: .
      dockerfile: src/Client/Tnosc.Shop.Client.Host.Web/Tnosc.Shop.Client.Host.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker


  tnosc.shop.bff:
    image: ${DOCKER_REGISTRY-}tnoscshopbff
    build:
      context: .
      dockerfile: src/Gateway/Tnosc.Shop.BFF/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
